"""add is_anonymous and description to circles

Revision ID: 83b1ebd4d9d6
Revises: 3cb1a19e5029
Create Date: 2026-04-21 20:01:50.560821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b1ebd4d9d6'
down_revision: Union[str, None] = '3cb1a19e5029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circles', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.alter_column('circles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('circles', 'is_anonymous')
    # ### end Alembic commands ###
