"""add order to memberships

Revision ID: 3cb1a19e5029
Revises: 4880ba0ee49f
Create Date: 2026-04-21 19:44:05.784493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb1a19e5029'
down_revision: Union[str, None] = '4880ba0ee49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'order')
    # ### end Alembic commands ###
